/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BreatheEasySim.Components;

/**
 *
 * @author kyleh
 */
public class Gauge extends javax.swing.JPanel {
    private float min = 0;
    private float max = 100;
    private boolean isInt = true;

    /**
     * Creates new form Gauge
     */
    public Gauge() {
        initComponents();
        genericGauge.setMaximum((int)max);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new BreatheEasySim.Components.GenericImageLabel();
        jLabel4 = new javax.swing.JLabel();
        genericGauge = new BreatheEasySim.Components.GenericGauge();
        jLabel2 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BreatheEasySim/Images/Gauge Label.png"))); // NOI18N
        label.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Name");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        label.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 150, 40));

        add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 110));

        genericGauge.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        genericGauge.setGaugeSize(6);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Unit");

        javax.swing.GroupLayout genericGaugeLayout = new javax.swing.GroupLayout(genericGauge);
        genericGauge.setLayout(genericGaugeLayout);
        genericGaugeLayout.setHorizontalGroup(
            genericGaugeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, genericGaugeLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        genericGaugeLayout.setVerticalGroup(
            genericGaugeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, genericGaugeLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(genericGauge, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 120));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BreatheEasySim.Components.GenericGauge genericGauge;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel4;
    private BreatheEasySim.Components.GenericImageLabel label;
    // End of variables declaration//GEN-END:variables

    
    
    public void changeValue(int val) {
        genericGauge.setValue(val);
    }
    
    public float getMax() {
        return max;
    }
    
    public void setMax(float m) {
        max = m;
    }

    public float getMin() {
        return min;
    }

    public void setMin(float min) {
        this.min = min;
    }

    public boolean isIsInt() {
        return isInt;
    }

    public void setIsInt(boolean isInt) {
        this.isInt = isInt;
    }
    
    

}
