/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BreatheEasySim.Components;

/**
 *
 * @author kyleh
 */
public class MainBottomPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManeBottomPanel
     */
    public MainBottomPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purpleCurveButton1 = new BreatheEasySim.Components.GenericImageLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        purpleCurveButton2 = new BreatheEasySim.Components.GenericImageLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        purpleCurveButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BreatheEasySim/Images/Bottom Label.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("L");
        purpleCurveButton1.add(jLabel1);
        jLabel1.setBounds(207, 0, 75, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Calcve");
        purpleCurveButton1.add(jLabel2);
        jLabel2.setBounds(3, 0, 75, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("4.80");
        purpleCurveButton1.add(jLabel3);
        jLabel3.setBounds(0, 10, 287, 40);

        add(purpleCurveButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 288, 59));

        purpleCurveButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BreatheEasySim/Images/Bottom Label.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("L");
        purpleCurveButton2.add(jLabel4);
        jLabel4.setBounds(207, 0, 75, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Calcve");
        purpleCurveButton2.add(jLabel5);
        jLabel5.setBounds(3, 0, 75, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("1:8.4");
        purpleCurveButton2.add(jLabel6);
        jLabel6.setBounds(0, 10, 287, 40);

        add(purpleCurveButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 288, 59));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private BreatheEasySim.Components.GenericImageLabel purpleCurveButton1;
    private BreatheEasySim.Components.GenericImageLabel purpleCurveButton2;
    // End of variables declaration//GEN-END:variables
}
