/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BreatheEasySim.Components;

/**
 *
 * @author kyleh
 */
public class MainGaugePanel extends javax.swing.JPanel {

    /**
     * Creates new form MainGaugePanel
     */
    public MainGaugePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gauge1 = new BreatheEasySim.Components.Gauge();
        gauge2 = new BreatheEasySim.Components.Gauge();
        gauge3 = new BreatheEasySim.Components.Gauge();
        gauge4 = new BreatheEasySim.Components.Gauge();
        gauge5 = new BreatheEasySim.Components.Gauge();
        gauge6 = new BreatheEasySim.Components.Gauge();
        gauge7 = new BreatheEasySim.Components.Gauge();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(gauge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 0, 180, 141));
        add(gauge2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 180, 141));
        add(gauge3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 180, 141));
        add(gauge4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 180, 141));
        add(gauge5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 180, 141));
        add(gauge6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 0, 180, 141));
        add(gauge7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 0, 180, 141));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BreatheEasySim.Components.Gauge gauge1;
    private BreatheEasySim.Components.Gauge gauge2;
    private BreatheEasySim.Components.Gauge gauge3;
    private BreatheEasySim.Components.Gauge gauge4;
    private BreatheEasySim.Components.Gauge gauge5;
    private BreatheEasySim.Components.Gauge gauge6;
    private BreatheEasySim.Components.Gauge gauge7;
    // End of variables declaration//GEN-END:variables
}
