/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BreatheEasySim.Components;

/**
 *
 * @author kyleh
 */
public class UtilitiesDateTabGaugePanel extends javax.swing.JPanel {

    /**
     * Creates new form MainGaugePanel
     */
    public UtilitiesDateTabGaugePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gauge2 = new BreatheEasySim.Components.Gauge();
        gauge3 = new BreatheEasySim.Components.Gauge();
        gauge4 = new BreatheEasySim.Components.Gauge();
        gauge8 = new BreatheEasySim.Components.Gauge();
        gauge9 = new BreatheEasySim.Components.Gauge();

        setMinimumSize(new java.awt.Dimension(1600, 141));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1600, 141));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(gauge2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 180, 141));
        gauge2.jLabel4.setText("Month");

        add(gauge3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 180, 141));
        gauge3.jLabel4.setText("Day");

        add(gauge4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 180, 141));
        gauge4.jLabel4.setText("Year");

        add(gauge8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 180, 141));
        gauge8.jLabel4.setText("Minute");

        add(gauge9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 180, 141));
        gauge9.jLabel4.setText("Hour");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BreatheEasySim.Components.Gauge gauge2;
    private BreatheEasySim.Components.Gauge gauge3;
    private BreatheEasySim.Components.Gauge gauge4;
    private BreatheEasySim.Components.Gauge gauge8;
    private BreatheEasySim.Components.Gauge gauge9;
    // End of variables declaration//GEN-END:variables
}
