/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BreatheEasySim.Popups;

/**
 *
 * @author calebgomez
 */
public class Startup extends javax.swing.JPanel {
    public int resume = 0;
    public int patient = 0;
    /**
     * Creates new form Startup
     */
    public Startup() {
        initComponents();
        resumeCurrent.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                System.out.println("resumeCurrent clicked!");
                if (resume == 0) {
                    System.out.println("ILV Mode Off!");
                    resumeCurrent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BreatheEasySim/Images/Button OnClick.png")));
                    resumeCurrent.repaint();
                    newPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BreatheEasySim/Images/Button.png")));
                    newPatient.repaint();
                    resume = 1;
                    patient = 0;
                }
                else {
                    System.out.println("ILV Mode On!");
                    resumeCurrent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BreatheEasySim/Images/Button.png")));
                    resumeCurrent.repaint();
                    resume = 0;
                }
            }
        });
        newPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                System.out.println("resumeCurrent clicked!");
                if (patient == 0) {
                    System.out.println("ILV Mode Off!");
                    newPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BreatheEasySim/Images/Button OnClick.png")));
                    newPatient.repaint();
                    resumeCurrent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BreatheEasySim/Images/Button.png")));
                    resumeCurrent.repaint();
                    resume = 0;
                    patient = 1;
                }
                else {
                    System.out.println("ILV Mode On!");
                    newPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BreatheEasySim/Images/Button.png")));
                    newPatient.repaint();
                    patient = 0;
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        resumeCurrent = new BreatheEasySim.Components.GenericImageLabel();
        jLabel3 = new javax.swing.JLabel();
        patientAccept = new BreatheEasySim.Components.GenericImageLabel();
        jLabel2 = new javax.swing.JLabel();
        newPatient = new BreatheEasySim.Components.GenericImageLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(169, 170, 204));
        setForeground(new java.awt.Color(162, 164, 191));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PATIENT SELECT");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        resumeCurrent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BreatheEasySim/Images/Button.png"))); // NOI18N
        resumeCurrent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resumeCurrentMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html><body style='text-align: center'>Resume<br>Current</html>");
        resumeCurrent.add(jLabel3);
        jLabel3.setBounds(34, 18, 42, 30);

        add(resumeCurrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 64, 109, 67));

        patientAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BreatheEasySim/Images/Button.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html><body style='text-align: center'>Patient<br>Accept</html>");
        patientAccept.add(jLabel2);
        jLabel2.setBounds(35, 18, 42, 30);

        add(patientAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 203, 109, 67));

        newPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BreatheEasySim/Images/Button.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<html><body style='text-align: center'>New<br>Patient</html>");
        newPatient.add(jLabel8);
        jLabel8.setBounds(35, 18, 42, 30);

        add(newPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 64, 109, 67));
    }// </editor-fold>//GEN-END:initComponents

    private void resumeCurrentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resumeCurrentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_resumeCurrentMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private BreatheEasySim.Components.GenericImageLabel newPatient;
    public BreatheEasySim.Components.GenericImageLabel patientAccept;
    public BreatheEasySim.Components.GenericImageLabel resumeCurrent;
    // End of variables declaration//GEN-END:variables
}
